# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='account_type',
            field=models.CharField(choices=[('LEC', 'Lecturer'), ('STUD', 'Student')], default='STUD', help_text='Choose between lecture or student', max_length=9),
        ),
    ]
