# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pic',
            field=models.ImageField(blank=True, default='', max_length=300, upload_to='users/uploads/account_pic/'),
        ),
    ]
