# Generated by Django 2.0.3 on 2018-03-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180319_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pic',
            field=models.ImageField(blank=True, default='', max_length=300, upload_to='users/uploads/account_pic/%Y-%m-%d/', verbose_name='Profile Picture'),
        ),
    ]
