# Generated by Django 2.0.3 on 2018-03-27 02:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180322_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pic',
            field=models.ImageField(blank=True, default='', max_length=300, upload_to=users.models.profile_picture_directory, verbose_name='Profile Picture'),
        ),
    ]
