# Generated by Django 2.0.6 on 2018-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180327_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='progressLevel',
            field=models.IntegerField(default=1),
        ),
    ]
