# Generated by Django 2.0.6 on 2018-07-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180725_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.ForeignKey(blank=True, db_column='level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_level', to='quiz.Category'),
        ),
    ]
