# Generated by Django 2.0.6 on 2018-07-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180725_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='level',
        ),
    ]
