# Generated by Django 2.0.6 on 2018-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(help_text='a user friendly url', max_length=80, verbose_name='user friendly url'),
        ),
    ]
