"""
Django settings for quiz_site project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ts1d=n2jvetwgem17%=#5xd(zp0ek999e$cy-dg8n40ipi16d)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # for application[ django-extensions ]
    'django_extensions',

    # for application[ users ]
    'users',

    # for application[ quiz ]
    'quiz',
    'multichoice',
    'true_false',
    'essay',

    'import_export',

    'jchart',

    # for application[ qa ]
    #'qa',
    #'taggit',
    #'hitcount',
    #'django_markdown',

    # testing bootstrap3
    #'django-bootstrap3',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quiz_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # /home/kibuthi-a/Documents/django_projects/quiz_site/quiz_site/templates
            r'/home/kibuthi-a/Documents/django_projects/quiz_site/quiz_site/templates',
            r'/home/kibuthi-a/Documents/django_projects/quiz_site/quiz/templates',
            r'/home/kibuthi-a/Documents/django_projects/quiz_site/users/templates',
            r'/home/kibuthi-a/Documents/django_projects/quiz_site/qa/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media', # to access MEDIA_URL in template
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quiz_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        # new configuration settings for connecting to POSTGRESQL

        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'quiz_site',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        # 'PORT': '5432', - previous setting
        'PORT': '5433',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join( BASE_DIR, 'static' )

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join( BASE_DIR, 'media' )

# for app: import_export
IMPORT_EXPORT_USE_TRANSACTIONS = True

# for application[ qa ]
#QA_SETTINGS = {
    #'qa_messages': True,
    #'qa_description_optional': False,
    #'count_hits': True,
    #'reputation': {
        #'CREATE_QUESTION': 0,
        #'CREATE_ANSWER': 0,
        #'CREATE_ANSWER_COMMENT': 0,
        #'CREATE_QUESTION_COMMENT': 0,
        #'ACCEPT_ANSWER': 0,
        #'UPVOTE_QUESTION': 0,
        #'UPVOTE_ANSWER': 0,
        #'DOWNVOTE_QUESTION': 0,
        #'DOWNVOTE_ANSWER': 0,
    #}
#}